### ISSUE TITLE
执行git submodule update命令时出错

### ISSUE THREAD

**Issue by fhchina** [zixun/CocoaChinaPlus#11]
Cloning into 'Code/CocoaChinaPlus/Application/Vender/vender-lib'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:zixun/vender-lib.git' into submodule path 'Code/CocoaChinaPlus/Application/Vender/vender-lib' failed

**Comment by zixun** [comment]
设置下SSH key即可 https://help.github.com/articles/generating-an-ssh-key/
