### ISSUE TITLE
CCCocoaChinaWebView crash issue

### ISSUE THREAD

**Issue by DaidoujiChen** [zixun/CocoaChinaPlus#5]
Hello @zixun,

在驗證修改的過程中, 發現 [CCCocoaChinaWebView](https://github.com/zixun/CocoaChinaPlus/blob/master/Code%2FCocoaChinaPlus%2FApplication%2FBusiness%2FUtil%2FView%2FCCocoaChinaWebView%2FCCCocoaChinaWebView.swift#L69) 這個地方, 會有回調回來的 image 為 nil 造成 crash 的狀況, 晚些完成手邊的部分, 回頭來看這個問題, 謝謝.

**Comment by zixun** [comment]
恩~赞。我最近手头工作比较忙，今天才有时间上来看看 @DaidoujiChen
