### ISSUE TITLE
做Pod update时候报错

### ISSUE THREAD

**Issue by wongben** [zixun/CocoaChinaPlus#9]
[!] Error installing R.swift
[!] /usr/bin/curl -f -L -o /var/folders/zb/mcy3fz6161v6pvy2z1vvhgg00000gn/T/d20151202-26748-1e6ntk3/file.zip https://github.com/mac-cain13/R.swift/releases/download/v0.12.0/rswift-0.12.0.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   594    0   594    0     0    141      0 --:--:--  0:00:04 --:--:--   141
  7 1398k    7  101k    0     0    194      0  2:03:01  0:08:55  1:54:06     0curl: (56) SSLRead() return error -9806

**Comment by zixun** [comment]
@wongben 我试了一下没问题，你再试一次 应该是网络问题超时了

**Comment by Demonsword27** [comment]
我出现了和楼上一样的问题，试了一下午 不知道该怎么解决

**Comment by zixun** [comment]
@Wbqqqq 试试翻墙后再运行看
